spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nonpossodirlo@gmail.com
    password: nonpossodirlo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
